site_name: Victoria 1st Year Tech Wiki
nav:
  - Home:
    - index.md
  - MATH132:
    - math/132/index.md
    - Week 1:
      - Number Sets: math/132/2025-02-24-number-sets.md
      - Rational Numbers: math/132/2025-02-27-rational-numbers.md
      - Exponentials and Fractions: math/132/2025-02-28-exponentials-and-fractions.md
    - Week 2:
      - Fractions and Negative Numbers: math/132/2025-03-03-fractions-and-negative-numbers.md
      - Inequalities and Different Number Systems: math/132/2025-03-06-inequalities-and-different-number-systems.md

theme:
  name: material
  language: "en"
  icon:
    logo: fontawesome/solid/book-open
  palette:
    # 'default' for light mode, 'slate' for dark mode
    # scheme: default

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy # Code blocks all have copy-to-clipboard buttons
    - content.action.edit # Edit button
    - content.action.view # View source button
    - navigation.instant  # Clicks on all internal links will be intercepted
                        # and dispatched without fully reloading the page
    - navigation.instant.progress # Progress indicator
    # - navigation.tracking # Changes the URL state at the top to the current
                            # heading
    - navigation.tabs # Tabs up the top
    - navigation.tabs.sticky  # Sticky tabs
    - navigation.sections # Expands all top-level page sections
    # - navigation.expand # If the above is not active, this will expand all
                        # sections
    - navigation.prune  # Not compatible with `expand`, reduces build size
    - navigation.indexes  # Attaches documents directly to sections
    - toc.follow  # Scrolls the sidebar to follow when jumping sections
    # - toc.integrate # Moves the sidebar to the left into the sections
    - navigation.top  # "Back to top" button
    - search.suggest  # Suggest searches
    - search.highlight  # Highlights all results in the search
    - search.share  # Allows deep links to the search
    - navigation.footer

    # Reference
    - content.tooltips
    - header.autohide

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors:
      show_contribution: true
      show_line_count: true
      show_email_address: false # No need for this
      fallback_to_empty: false
      sort_authors_by: contribution
      authorship_threshold_percent: 0 # Default
      exclude:
        - index.md
      enabled: true
      strict: true
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true
  - macros
  # - macros
  # - blog
  # - tags:
  # - enabled: true
  # tags_file: tags.md
  # - rss:
  #     match_path: blog/posts/.*
  #     date_from_meta:
  #         as_creation: "date"
  #     categories:
  #         - categories
  #         - tags
  #     comments_path: "#__comments"

markdown_extensions:
  - abbr
  - attr_list
  - footnotes
  - admonition
  - def_list
  - md_in_html
  - tables
  - pymdownx.superfences
  - pymdownx.betterem     # Better detection of emphasis in Markdown
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  # - pymdownx.keys
  # - pymdownx.highlight:
  #   anchor_linenums: true
  #   auto_title: true
  - pymdownx.snippets:
      auto_append:
          - includes/abbreviations.md
          # - includes/footnotes.md
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/CzdC6d2WDc
      name: First Year Technology Students Discord

repo_name: victech2025/victech2025.github.io
repo_url: https://github.com/victech2025/victech2025.github.io
edit_uri: edit/main/docs/

watch:
    - includes

extra_javascript:
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
